name: Workflow using my own action
on: [push]
jobs:
  passrepo:
    runs-on: ubuntu-latest
    steps:
    - name: STEP_1 Dump GitHub context
    - uses: actions/biopypir-python-action@master
      with:
        myrepo: ${{ toJson(github.repository) }} 

