name: Workflow using my own action
on: [push]
jobs:
  passrepo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/biopypir-python-action@master
      with:
         myrepo: ${{ toJson(github.repository) }} 

