name: Workflow using my own action
on: [push]
jobs:
  passrepo:
    runs-on: ubuntu-latest
    steps:
    - name: STEP_1 Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
          
    #- uses: benstear/biopypir-python-action@master
    #  with:
    #    myrepo: benstear/DL-chd

