name: Workflow using my own action
on: [push]
jobs:
  passrepo:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
          python-version: "3.7"
    - uses: actions/checkout@v2
      
    - uses: benstear/biopypir-python-action@master
      
      with:
         myrepo: ${{ toJson(github.repository) }} 

